# Generated by Django 5.1.6 on 2025-03-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_taskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Открыто'), (2, 'В работе'), (3, 'Исполнено'), (4, 'Закрыто')], default=1),
        ),
        migrations.DeleteModel(
            name='ProjectComment',
        ),
    ]
